window.BJ_TRAINING_GUIDES = {
  "backtracking": "# 回溯\n\n## 适用信号\n\n- 全排列、组合、子集\n- 需要枚举所有方案\n- 有选择、撤销选择、剪枝\n\n## 固定框架\n\n```python\npath = []\nanswer = []\n\ndef backtrack(start):\n    if is_complete(path):\n        answer.append(path[:])\n        return\n\n    for i in range(start, len(candidates)):\n        if should_skip(i):\n            continue\n        path.append(candidates[i])\n        backtrack(next_start(i))\n        path.pop()\n```\n\n## 常见坑\n\n- 忘记 `path[:]` 复制\n- 去重条件写错\n- 组合和排列的 `start` 语义混淆\n",
  "binary-search": "# 二分查找\n\n## 适用信号\n\n- 有序数组或局部有序结构\n- 要求 `O(log n)`\n- 查找边界、最小可行值、最大可行值\n\n## 固定框架：闭区间\n\n```python\nleft, right = 0, len(nums) - 1\n\nwhile left <= right:\n    mid = (left + right) // 2\n    if nums[mid] == target:\n        return mid\n    if should_go_left(mid):\n        right = mid - 1\n    else:\n        left = mid + 1\n\nreturn -1\n```\n\n## 固定框架：答案二分\n\n```python\nleft, right = min_value, max_value\n\nwhile left < right:\n    mid = (left + right) // 2\n    if feasible(mid):\n        right = mid\n    else:\n        left = mid + 1\n\nreturn left\n```\n\n## 常见坑\n\n- `left <= right` 和 `left < right` 混用\n- `mid` 更新后边界不收缩导致死循环\n- 旋转数组中没有先判断哪一侧有序\n",
  "dynamic-programming": "# 动态规划\n\n## 适用信号\n\n- 最优值、方案数、可行性\n- 子问题有重叠\n- 当前状态可由更小状态转移得到\n\n## 固定拆解\n\n1. 定义状态：`dp[i]` 或 `dp[i][j]` 表示什么。\n2. 写转移：当前状态从哪些旧状态来。\n3. 初始化：最小子问题是什么。\n4. 遍历顺序：保证依赖状态已经算好。\n5. 返回答案：返回哪个状态。\n\n## 一维 DP 框架\n\n```python\ndp = [initial] * (n + 1)\ndp[0] = base\n\nfor i in range(1, n + 1):\n    for choice in choices:\n        dp[i] = update(dp[i], dp[previous_state])\n```\n\n## 常见坑\n\n- 状态定义含糊\n- 初始化和返回值不匹配\n- 01 背包和完全背包遍历方向混淆\n",
  "graph-search": "# 图搜索\n\n## 适用信号\n\n- 岛屿数量、连通块\n- 最短路径\n- 拓扑排序\n- 网格搜索\n\n## DFS 网格框架\n\n```python\ndef dfs(r, c):\n    if out_of_bound(r, c) or visited_or_blocked(r, c):\n        return\n    mark_visited(r, c)\n    for dr, dc in directions:\n        dfs(r + dr, c + dc)\n```\n\n## BFS 最短路框架\n\n```python\nfrom collections import deque\n\nqueue = deque([(start, 0)])\nvisited = {start}\n\nwhile queue:\n    node, dist = queue.popleft()\n    if is_target(node):\n        return dist\n    for nxt in neighbors(node):\n        if nxt not in visited:\n            visited.add(nxt)\n            queue.append((nxt, dist + 1))\n```\n\n## 常见坑\n\n- 访问标记太晚导致重复入队\n- 网格边界判断遗漏\n- DFS 递归深度过大时需要改迭代或 BFS\n",
  "hash-table": "# 哈希表\n\n## 适用信号\n\n- 快速查找是否出现过\n- 计数、分组、映射关系\n- 需要把 `O(n^2)` 查找降到 `O(n)`\n\n## 固定框架\n\n```python\nseen = {}\n\nfor index, value in enumerate(nums):\n    key = build_key(value)\n    if need(key) in seen:\n        return build_answer(seen[need(key)], index)\n    seen[key] = index\n```\n\n## 常见坑\n\n- 先查再存，还是先存再查，要看是否允许使用当前元素\n- key 设计错误，比如异位词分组时没有排序或计数\n- 覆盖旧下标导致边界错误\n",
  "heap-topk": "# 堆与 TopK\n\n## 适用信号\n\n- 第 K 大 / 第 K 小\n- 动态维护最值\n- 合并多个有序结构\n\n## 固定框架\n\n```python\nimport heapq\n\nheap = []\nfor value in nums:\n    heapq.heappush(heap, value)\n    if len(heap) > k:\n        heapq.heappop(heap)\n\nreturn heap[0]\n```\n\n## 常见坑\n\n- Python 默认是小根堆\n- 第 K 大通常维护大小为 K 的小根堆\n- 复杂度是 `O(n log k)`，不是 `O(n log n)`\n",
  "linked-list": "# 链表\n\n## 适用信号\n\n- 反转、合并、删除节点\n- 快慢指针\n- 需要 dummy node 简化头节点处理\n\n## 反转框架\n\n```python\nprev = None\ncur = head\n\nwhile cur:\n    nxt = cur.next\n    cur.next = prev\n    prev = cur\n    cur = nxt\n\nreturn prev\n```\n\n## 常见坑\n\n- 断链前没有保存 `next`\n- 删除头节点时没有使用 dummy\n- 快慢指针终止条件不清楚\n",
  "prefix-sum": "# 前缀和\n\n## 适用信号\n\n- 子数组和\n- 区间和查询\n- 需要把区间和转为两个前缀差\n\n## 固定框架\n\n```python\ncount = 0\nprefix = 0\nseen = {0: 1}\n\nfor value in nums:\n    prefix += value\n    count += seen.get(prefix - target, 0)\n    seen[prefix] = seen.get(prefix, 0) + 1\n```\n\n## 常见坑\n\n- 忘记初始化 `{0: 1}`\n- 子数组必须连续\n- 负数存在时不能用滑动窗口替代前缀和\n",
  "sliding-window": "# 滑动窗口\n\n## 适用信号\n\n- 连续子数组或连续子串\n- 最长、最短、满足条件的区间\n- 题目可以通过移动左右边界维护状态\n\n## 固定框架\n\n```python\nleft = 0\nstate = ...\nanswer = ...\n\nfor right, value in enumerate(nums):\n    add(value)\n\n    while window_is_invalid():\n        remove(nums[left])\n        left += 1\n\n    answer = update(answer, left, right, state)\n```\n\n## 面试讲法\n\n窗口内维护一个可快速判断合法性的状态。右边界负责扩张，左边界负责恢复合法性。只要每个元素最多进出窗口一次，总复杂度就是 `O(n)`。\n\n## 常见坑\n\n- 左边界回退\n- 更新答案的位置不对\n- `while` 和 `if` 的选择不对\n- 忘记在左边界移动时同步删除状态\n",
  "stack": "# 栈与单调栈\n\n## 适用信号\n\n- 最近一个更大 / 更小元素\n- 括号匹配\n- 需要维护一个单调结构\n\n## 单调栈框架\n\n```python\nstack = []\nanswer = default_answer()\n\nfor i, value in enumerate(nums):\n    while stack and should_pop(nums[stack[-1]], value):\n        j = stack.pop()\n        answer[j] = build_answer(j, i)\n    stack.append(i)\n```\n\n## 常见坑\n\n- 栈里存值还是下标要想清楚\n- 单调递增和单调递减方向写反\n- 没处理栈中最后没有匹配的元素\n",
  "tree": "# 二叉树\n\n## 适用信号\n\n- DFS 递归\n- BFS 层序遍历\n- 二叉搜索树性质\n- 最近公共祖先\n\n## DFS 框架\n\n```python\ndef dfs(node):\n    if not node:\n        return base_value\n\n    left = dfs(node.left)\n    right = dfs(node.right)\n    return combine(node, left, right)\n```\n\n## BFS 框架\n\n```python\nfrom collections import deque\n\nqueue = deque([root])\nwhile queue:\n    for _ in range(len(queue)):\n        node = queue.popleft()\n        handle(node)\n        if node.left:\n            queue.append(node.left)\n        if node.right:\n            queue.append(node.right)\n```\n\n## 常见坑\n\n- 递归返回值没有定义清楚\n- BST 只比较父子节点，没有传上下界\n- 层序遍历没有固定当前层长度\n",
  "two-pointers": "# 双指针\n\n## 适用信号\n\n- 数组、链表、字符串两端移动\n- 有序数组中的二数和、三数和\n- 原地删除、合并、反转\n\n## 固定框架\n\n```python\nleft, right = 0, len(nums) - 1\n\nwhile left < right:\n    current = combine(nums[left], nums[right])\n    if current == target:\n        handle_answer()\n        left += 1\n        right -= 1\n    elif current < target:\n        left += 1\n    else:\n        right -= 1\n```\n\n## 常见坑\n\n- 去重逻辑不完整\n- 指针移动条件写反\n- 忘记有序性是双指针成立的前提之一\n",
  "lc-0003-longest-substring": "# LC 3 Longest Substring Without Repeating Characters 复盘\n\n## 完成状态\n\n- 状态：已完成\n- 题型：滑动窗口 + 哈希表\n- 本地样例：全部通过\n- 额外验证：固定边界用例 + 200 个随机用例，与暴力解交叉校验一致\n\n## 你的表现\n\n你的实现采用 `set + 双指针`。右指针尽量向右扩张，遇到重复字符后，左指针逐步收缩并维护窗口集合。整体思路正确，复杂度达到 `O(n)`。\n\n## 关键不变量\n\n`record` 始终表示当前窗口 `s[i:ind]` 中的字符集合，并且窗口内没有重复字符。\n\n## 做得好的地方\n\n- 能用滑动窗口维护无重复区间。\n- 能正确处理 `abba` 这类容易让左边界回退的样例。\n- 能通过全重复、全不重复、重复分散等常见边界。\n\n## 可优化点\n\n- `ret = -1` 加空字符串特判可以工作，但面试里更推荐初始化为 `0`，这样空字符串自然返回 `0`。\n- 讲解时要强调“每个字符最多入窗一次、出窗一次”，这正是 `O(n)` 的原因。\n\n## 面试表达模板\n\n这题用滑动窗口。窗口维护当前没有重复字符的子串。右指针不断扩张，如果下一个字符已经在窗口中，就移动左指针并删除字符，直到窗口重新合法。每次窗口合法时更新最大长度。因为每个字符最多被加入和删除一次，所以时间复杂度是 `O(n)`。\n"
};
